json:
  apt:
    mirror: de
  nodejs:
    versions:
      - 0.6.21
      - 0.8.8
      - 0.9.1
    aliases:
      0.6.21: 0.6
      0.8.8: 0.8
      0.9.1: 0.9
    default: 0.6.21
recipes:
  - haskell
  - java::multi
  - ant
  - maven3
  - leiningen
  - sbt
  - gradle::tarball
  - kerl
  - rebar
  # Node.js is now co-hosted, too
  - nodejs::multi
  - sweeper