memory: 1536
json:
  rvm:
    default: 1.9.3
    rubies:
    - name: jruby-d19
      arguments: --19
      check_for: jruby-d19
    - name: ree
    - name: 1.9.2
      # using commit from https://github.com/ruby/ruby/commit/6f8bce9eff15b527c87e1b13312db2fbf0b504f4
    - name: ruby-head-s6f8bce9eff15b527c87e1b13312db2fbf0b504f4
    - name: jruby-head
    - name: ruby-2.0.0-rc1
    gems:
      - bundler
      - rake
    aliases:
      jruby-18mode: jruby-d18
      jruby-19mode: jruby-d19
      jruby: jruby-19mode
      "2.0": "ruby-2.0.0-rc1"
recipes:
  - sysctl
  - travis_build_environment
  - sweeper
  - rvm
  - rvm::multi
  - java::multi
  - sweeper
