json:
  mysql:
    server_root_password: ""
  postgresql:
    max_connections: 256
  travis_build_environment:
    use_tmpfs_for_builds: true
  rvm:
    default: 1.9.3
    rubies:
    - name: 1.9.3
    gems:
      - bundler
      - rake
  recipes:
    - php::multi
