json:
  nodejs:
    versions:
      - 0.6.21
      - 0.8.18
      - 0.9.8
    aliases:
      0.6.21: 0.6
      0.8.18: 0.8
      0.9.8: 0.9
    default: 0.8.18
recipes:
  - haskell
  - java::multi
  - ant
  - maven3
  - leiningen
  - sbt
  - gradle::tarball
  - kerl
  - rebar
  # Node.js is now co-hosted, too
  - nodejs::multi
  - sweeper