json:
  nodejs:
    versions:
      - 0.4.12
      - 0.6.19
      - 0.8.4
      - 0.9.0
    aliases:
      0.4.12: 0.4
      0.6.19: 0.6
      0.8.4: 0.8
      0.9.0: 0.9
    default: 0.6.19
recipes:
  - haskell
  - java::multi
  - ant
  - maven3
  - leiningen
  - sbt
  - gradle::tarball
  - kerl
  - rebar
  # Node.js is now co-hosted, too
  - nodejs::multi
  - sweeper