json:
  mysql:
    server_root_password: ""
  postgresql:
    max_connections: 256
  travis_build_environment:
    use_tmpfs_for_builds: true
recipes:
  - travis_build_environment
  - apt
  - build-essential
  - networking_basic
  - openssl
  - sysctl
  - libyaml
  - emacs::nox
  - timetrap
  - git
  - sqlite
  - postgresql::client
  - mysql::client
  - php::multi
  - postgresql::server
  - mysql::server
  - scons
  - libqt4
  - libv8
  - nodejs::multi
  - redis
  - riak
  - mongodb
  - memcached
  - rabbitmq::with_management_plugin
  - imagemagick
  - sphinx::all
  - xserver
  - vim
