memory: 1536
json:
  rvm:
    default: 1.8.7
    rubies:
    - name: 1.9.3
    - name: rbx-head
      arguments: --branch 2.0.testing
      using: 1.8.7
    - name: 1.8.7
    - name: jruby
    - name: ree
    - name: 1.9.2
    - name: ruby-head
    gems:
      - bundler
      - rake
      - chef
    aliases:
      rbx: rbx-head
      rbx-2.0: rbx-head
      rbx-2.0.0pre: rbx-head
      rbx-18mode: rbx-head
recipes:
  - rvm
  - rvm::multi
  - mysql::server_on_ramfs
  - postgresql::server_on_ramfs
