json:
  nodejs:
    versions:
      - 0.6.21
      - 0.8.17
      - 0.9.6
    aliases:
      0.6.21: 0.6
      0.8.17: 0.8
      0.9.6: 0.9
    default: 0.8.17
recipes:
  - haskell
  - java::multi
  - ant
  - maven3
  - leiningen
  - sbt
  - gradle::tarball
  - kerl
  - rebar
  - nodejs::multi
  - sweeper