json:
  apt:
    mirror: de
recipes:
  - perlbrew::multi
  - php::multi
  - composer
  - python::multi
  # composer and pip really benefit from these two being preinstalled. MK.
  - bazaar
  - subversion
  - sweeper
