memory: 1536
json:
  rvm:
    default: 1.8.7
    rubies:
    - name: 1.9.3
    - name: rbx-head
      arguments: --branch 2.0.testing
      using: 1.8.7
    - name: rbx-head
      arguments: -n d19 --branch 2.0.testing -- --default-version=1.9
      using: 1.9.3
      check_for: rbx-head-d19
    - name: 1.8.7
    - name: jruby
    - name: jruby-d19
      arguments: --19
      check_for: jruby-d19
    - name: ree
    - name: 1.9.2
    - name: ruby-head
    - name: jruby-head
    - name: 1.8.6
    gems:
      - bundler
      - rake
      - chef
    aliases:
      rbx: rbx-head
      rbx-2.0: rbx-head
      rbx-2.0.0pre: rbx-head
      rbx-18mode: rbx-head
      rbx-19mode: rbx-head-d19
      jruby-18mode: jruby
      jruby-19mode: jruby-d19
recipes:
  - rvm
  - rvm::multi
  - leiningen
  - sbt
