json:
  rvm:
    rubies:
      1.8.7: 1.8.7 
      rbx-head-1.8: rbx -n 1.8 -- --default-version=1.8  --branch 2.0.testing 
      rbx-head-1.9: rbx -n 1.9 -- --default-version=1.9  --branch 2.0.testing 
      jruby-1.6.4-18: jruby -n18 -C -Djruby.default.ruby.version=1.8 
      jruby-1.6.4-19: jruby -n19 -C -Djruby.default.ruby.version=1.9 
    gems:
      - bundler
      - rake
      - chef
    aliases:
      rbx-head-1.8: rbx18
      rbx-head-1.9: rbx19
      jruby-1.6.4-18: jruby18
      jruby-1.6.4-19: jruby19
  mysql:
    server_root_password: ""
  postgresql:
    max_connections: 256
recipes:
  - travis_build_environment
  - apt
  - build-essential
  - networking_basic
  - openssl
  - sysctl
  - libyaml # libyaml MUST be installed before rubies. MK.
  - git
  - java
  - ant
  - maven
  # # - scons
  # # - libv8
  # # - nodejs
  - rvm
  - rvm::multi
  # # - postgresql::client
  # # - postgresql::server
  # # - mysql::client
  # # - mysql::server_on_ramfs
  # # - memcached
