base: http://files.travis-ci.org/boxes/provisioned/travis-standard-pro.box
memory: 1536
json:
  rvm:
    default: 1.9.3
    rubies:
    - name: 1.8.7
    - name: rbx-head
      arguments: --branch 2.0.testing
      using: 1.8.7
    - name: rbx-head-d19
      arguments: --branch 2.0.testing --19
      using: 1.9.3
      check_for: rbx-head-d19
    - name: 1.8.7
    - name: jruby-d18
      arguments: --18
      check_for: jruby-d18
    - name: jruby-d19
      arguments: --19
      check_for: jruby-d19
    - name: ree
    - name: 1.9.2
    - name: 1.9.3-p194
      # using commit from https://github.com/ruby/ruby/commit/6f8bce9eff15b527c87e1b13312db2fbf0b504f4
    - name: ruby-head-s6f8bce9eff15b527c87e1b13312db2fbf0b504f4
    - name: jruby-head
    - name: ruby-2.0.0-preview2
    gems:
      - bundler
      - rake
    aliases:
      rbx: rbx-head
      rbx-18mode: rbx-head
      rbx-19mode: rbx-head-d19
      jruby-18mode: jruby-d18
      jruby-19mode: jruby-d19
      jruby: jruby-19mode
      "2.0": "ruby-2.0.0-preview2"
recipes:
  - sweeper
  - rvm
  - rvm::multi
  - java::multi
  - sweeper
