json:
  nodejs:
    versions:
      - 0.6.21
      - 0.8.22
      - 0.9.12
      - 0.10.1
    aliases:
      0.6.21: 0.6
      0.8.21: 0.8
      0.9.12: 0.9
      0.10.2: 0.10
    default: 0.8.22
recipes:
  - nodejs::multi
  - sweeper