recipes:
  - java
  - ant
  - maven3
  - leiningen
  - sbt
  - gradle::tarball
  # Erlang projects are hosted on the  JVM machine(s).
  - kerl
  - rebar
  # Haskell projects are hosted on the JVM machine(s).
  - haskell
